In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn import preprocessing
tf.set_random_seed(42)

In [2]:
s = tf.Session()
init = tf.global_variables_initializer()
s.run(init)

In [3]:
x =tf.random_normal([2,3])
y =tf.random_normal([2,3])
t = tf.random_normal(shape=(3,4))
t = tf.constant([[3.,4.],[2.,3.],[4.,5.]])

In [4]:
with tf.variable_scope('test') :
    
    t = tf.contrib.layers.linear(t, 1, scope='fc1')
    print(t)
    t = -tf.reduce_sum(t)
init = tf.global_variables_initializer()
s.run(init)
print(t)
data = s.run([t])
print(data)

Tensor("test/fc1/BiasAdd:0", shape=(3, 1), dtype=float32)
Tensor("test/Neg:0", shape=(), dtype=float32)
[14.893255]


In [98]:
train = tf.train.GradientDescentOptimizer(1e-3).minimize(t)
print(s.run([train, t]))
# fc1_val = tf.get_variable('test/fc1/weights/d')

[None, -6.8777485]


In [4]:
bat_x, bat_y = tf.train.batch(tensors=[x,y],batch_size=1, dynamic_pad=False)
# bat = tf.contrib.training.bucket_by_sequence_length(input_length=3, tensors=[x,y], batch_size=1)
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=s, coord=coord)


In [8]:
print(s.run([bat_x, bat_y]))

[array([[[-1.44549644,  1.31358135, -1.60024261],
        [ 1.06059265, -0.29766434, -0.71426326]]], dtype=float32), array([[[ -8.14662993e-01,   1.55203253e-01,   1.87591243e+00],
        [  3.93171698e-01,  -2.44468236e+00,  -1.34637242e-03]]], dtype=float32)]


In [3]:
a = (tf.range(3) * [10,10,3])
print(s.run(a))



[ 0 10  6]


In [75]:
varr = tf.Variable(tf.random_uniform(shape=[1], maxval=10, dtype=tf.float32))

s.run(tf.global_variables_initializer())


reduced = tf.reduce_sum(varr)
train = tf.train.GradientDescentOptimizer(0.01).minimize(reduced)
print(s.run([varr,train]))
s.run(reduced)


[array([ 1.8343811], dtype=float32), None]


1.8343811

In [77]:
s.run([reduced,train,varr])

[1.8143811, None, array([ 1.81438112], dtype=float32)]

In [66]:
sp_indices = tf.random_uniform(shape=[5,2], maxval=10, dtype=tf.int32)
alpha = tf.random_uniform(shape=[5], maxval=10, dtype=tf.int32)

sparsed = tf.sparse_to_dense(sp_indices, [10, 7], alpha, validate_indices=False,
                                                 name="att_sparse_to_dense")
# print(s.run([sp_indices,alpha,sparsed]))
print(s.run([sp_indices,alpha, sparsed]))

[array([[3, 3],
       [2, 3],
       [5, 2],
       [4, 6],
       [5, 2]]), array([2, 5, 0, 6, 7]), array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6],
       [0, 0, 7, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])]


In [6]:
labels = tf.range(10000) *1458
print(s.run(labels))

[       0     1458     2916 ..., 14575626 14577084 14578542]


In [9]:
X = tf.random_uniform(shape=[3,4,5], maxval=10, dtype=tf.int32)
print(s.run(X))

[[[2 7 7 2 0]
  [8 0 7 6 7]
  [9 6 6 9 1]
  [3 2 8 8 5]]

 [[8 7 9 8 1]
  [2 3 4 7 2]
  [1 8 2 2 3]
  [5 7 0 9 2]]

 [[4 7 3 2 5]
  [7 5 3 1 4]
  [4 0 1 4 0]
  [3 8 1 0 0]]]


In [14]:
x_reshaped = tf.reshape(X,[-1,5])
expand = tf.expand_dims(X,3)
print(s.run([X,x_reshaped, expand])[1].shape)

(12, 5)


In [10]:
input_data =tf.random_uniform(shape=[1,3] , maxval=10, dtype=tf.int32) 
embedding = tf.random_uniform(shape=[10,2] , maxval=10, dtype=tf.int32)
gathered = tf.gather(embedding, input_data)

inputs_, embedding_, gathered_ = s.run([input_data, embedding,gathered])


print(inputs_)
print(embedding_)
print(gathered_, gathered)

[[9 1 7]]
[[9 8]
 [9 5]
 [0 8]
 [1 0]
 [2 8]
 [3 1]
 [9 7]
 [2 1]
 [1 8]
 [1 4]]
[[[1 4]
  [9 5]
  [2 1]]] Tensor("Gather_2:0", shape=(1, 3, 2), dtype=int32)


In [220]:
input_data =tf.random_uniform(shape=[1,3] ,minval=-10 ,maxval=10, dtype=tf.int32) 
abss = tf.sign(input_data)
s.run([input_data,abss])

[array([[ 2, -2, -6]]), array([[ 1, -1, -1]])]

In [19]:
lt=["22","44","55"]
df = [1,2,3,4]
# lt.append(df)
lt.extend(df)
tuple(lt *2)

('22', '44', '55', 1, 2, 3, 4, '22', '44', '55', 1, 2, 3, 4)

In [83]:
cast_test = tf.cast(X, dtype=tf.bool)
s.run(y)

array([[-1.41211283, -0.57831031, -0.75640547],
       [-0.56167918, -2.10854745, -1.75196922],
       [ 1.48033059, -1.19437778, -0.73439193],
       [-0.48297727, -0.41073939,  1.78392351],
       [ 0.48129374, -1.17940354,  0.72481978],
       [-0.10496811, -0.31811568,  0.21208768],
       [-1.27551186, -0.74990308, -0.26338577],
       [ 0.19356929, -0.21194717, -1.84980297],
       [ 0.02437377,  1.05214   , -0.55775386],
       [-0.82035667, -1.07654941, -0.48308611],
       [ 0.43199149, -1.07883418,  1.06760204],
       [ 1.36018074,  1.26381958,  1.30093861],
       [ 1.11742103,  0.12374764,  1.90662074],
       [-0.94280595,  0.28615844,  0.57828796],
       [-0.16717513, -0.50508827, -1.96472681],
       [ 1.44028485, -1.18124712,  0.03504804]], dtype=float32)

In [111]:
m2 = tf.random_uniform(shape=[3,4], maxval=10, dtype=tf.int32)
m1 = tf.random_uniform(shape=[3,3,2], maxval=10, dtype=tf.int32)
reduced = tf.reduce_sum(m1,2)
test_size = 3
# m1_ = s.run(m1)
reshaped = tf.reshape(m2_, [-1, test_size])  # (batch*k, size)
# print(m1_)
reshaped_, reduced_, m1_ = s.run([reshaped,reduced,m1])
# print(m2_)
# print(reshaped_)
print(m1_)
print(reduced_)


[[[2 6]
  [4 7]
  [2 9]]

 [[7 2]
  [9 8]
  [9 0]]

 [[7 4]
  [5 9]
  [9 8]]]
[[ 8 11 11]
 [ 9 17  9]
 [11 14 17]]


In [115]:
print(m1_)
s.run(tf.minimum(m1_+1,4))

[[[2 6]
  [4 7]
  [2 9]]

 [[7 2]
  [9 8]
  [9 0]]

 [[7 4]
  [5 9]
  [9 8]]]


array([[[3, 4],
        [4, 4],
        [3, 4]],

       [[4, 3],
        [4, 4],
        [4, 1]],

       [[4, 4],
        [4, 4],
        [4, 4]]])

In [23]:
print(tf.shape(data))
print(data.shape)
print(data)

Tensor("Shape_5:0", shape=(2,), dtype=int32)
(3, 1)
[[ 0.457571  ]
 [-0.15787232]
 [ 0.05245945]]


In [2]:
y_one_hot = [[[0, 1, 0, 0],   # i 1
              [1, 0, 0, 0],   # h 0
              [0, 0, 1, 0],   # e 2
              [0, 0, 0, 3],   # l 3
              [0, 0, 0, 4],   # l 3
              [0, 0, 0, 5]]]  # o 4

argtest = tf.argmax(y_one_hot,1)
argtest_2 = tf.argmax(y_one_hot,2)
s = tf.Session()
s.run([argtest, argtest_2])

[array([[1, 0, 2, 5]], dtype=int64), array([[1, 0, 2, 3, 3, 3]], dtype=int64)]

In [3]:
embedding = tf.get_variable('variable_embedding', [128, 32])
s.run(tf.global_variables_initializer())
t = tf.nn.embedding_lookup(params=embedding, ids=[[0],[4]])
# tf.identity()
# tf.argmax()
# t = tf.reduce_max([2,31,4,5])
# tf.sequence_mask()


In [5]:
s.run(embedding)
# s.run(t)

array([[ 0.114669  , -0.00071345,  0.06677443, ..., -0.1298181 ,
        -0.06117569,  0.14669898],
       [ 0.08785665, -0.05807771,  0.19225189, ..., -0.100212  ,
         0.07535726, -0.05911684],
       [-0.04900821, -0.0079432 ,  0.05898544, ...,  0.1835174 ,
        -0.07373639, -0.02473161],
       ..., 
       [ 0.18895945,  0.16350222, -0.09569921, ...,  0.12499744,
        -0.01557086, -0.11011218],
       [-0.0050191 ,  0.0099555 ,  0.00597554, ..., -0.17203383,
        -0.10057817,  0.08145738],
       [-0.00075492,  0.05036263, -0.02716316, ..., -0.08613453,
        -0.16590865,  0.10215229]], dtype=float32)

In [11]:
from tensorflow.python.util import nest
tiled = tf.tile([[22,2,3]],(10,nest.flatten([256])[0]))
print(tiled)

Tensor("Tile_2:0", shape=(10, 768), dtype=int32)


In [6]:
tf.tile([[2,1,3]],[3,2])

<tf.Tensor 'Tile_1:0' shape=(3, 6) dtype=int32>

In [7]:
nest_pack_sequence = nest.pack_sequence_as(structure=256, flat_sequence=[tiled])
print(nest_pack_sequence)

Tensor("Tile:0", shape=(10, 768), dtype=int32)


In [46]:
tf_expanded_dims = tf.expand_dims(nest_pack_sequence,1)
print(tf_expanded_dims)

Tensor("ExpandDims_3:0", shape=(10, 1, 768), dtype=int32)


In [44]:
from tensorflow.python.ops.gen_array_ops import _concat_v2 as concat_v2

In [61]:
tf_rand_normed = tf.random_uniform([10,1,768], maxval=10, dtype=tf.int32)
concat_v2([tf_expanded_dims, tf_rand_normed], 1)
# tf.constant()


<tf.Tensor 'ConcatV2_3:0' shape=(10, 2, 768) dtype=int32>

In [60]:
tf_normal = tf.random_normal(shape=[128,10])
replicated_first_indices = tf.range(tf.shape(tf_normal)[0])
print('replicated_first_indices', replicated_first_indices)
print('tf_normal_get_shape', tf_normal.get_shape())
normal = s.run(tf_normal)
replicated = tf.range(tf.shape(normal)[0])
replicated = s.run(replicated)
print('normal.shape',normal.shape)
print(replicated.shape)
print(replicated)

replicated_first_indices Tensor("range_51:0", shape=(?,), dtype=int32)
tf_normal_get_shape (128, 10)
normal.shape (128, 10)
(128,)
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127]


In [59]:
expanded = s.run(tf.expand_dims(replicated,dim=0))
print(expanded.shape)
print(expanded)

(1, 128)
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
   36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
   54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
   72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
   90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
  108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
  126 127]]


In [10]:
a = tf.constant(np.array([[.1,.3,.5,.9],
                          [.01,.03,.10,.09]
                         ]))
s = tf.Session()
b = tf.nn.softmax(a)
argmxtext = tf.arg_max(a,1)
argmxtext = tf.argmax(a,1)
before_softmax, after_softmax, argm = s.run([a,b, argmxtext])
print(before_softmax)
print(after_softmax)
print(argm)

[[ 0.1   0.3   0.5   0.9 ]
 [ 0.01  0.03  0.1   0.09]]
[[ 0.16838508  0.205666    0.25120102  0.37474789]
 [ 0.23822781  0.24304033  0.26066275  0.25806911]]
[3 2]


In [8]:
c = tf.reduce_sum(a)
d = tf.reduce_mean(a)
reduced_sum, reduce_mean  = s.run([c,d])
print(reduced_sum, reduce_mean)

1.8 0.45


In [10]:
x = [[1,2,3],[3,3,502]]
e = tf.reduce_sum(x, axis=0)
f = tf.reduce_sum(x, axis=1)
row_sum, column_sum = s.run([e,f])
print(row_sum, column_sum)

[  4   5 505] [  6 508]


In [11]:
normal_x = preprocessing.normalize(x)
print(normal_x)

[[ 0.26726124  0.53452248  0.80178373]
 [ 0.00597588  0.00597588  0.99996429]]


In [16]:
a = tf.constant([2,3])
g = s.run([a])
print(g)

[array([2, 3])]


In [2]:

dd = tf.sigmoid(tf.constant([-.10,-20,200]))
logted_ = tf.log(dd)
meand = tf.reduce_mean(logted_)
ssd, logted, mea = s.run([dd, logted_, meand])
print(ssd, logted, mea)

NameError: name 's' is not defined

In [34]:
dd = tf.constant([.01102030239029302390])
s = tf.Session()
da = tf.clip_by_value(dd, clip_value_max=1-1e-2, clip_value_min=1e-2)
print(s.run([dd, da]))

[array([ 0.0110203], dtype=float32), array([ 0.0110203], dtype=float32)]
