In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [2]:
y_one_hot = [[[0, 1, 0, 0],   # i 1
              [1, 0, 0, 0],   # h 0
              [0, 0, 1, 0],   # e 2
              [0, 0, 0, 3],   # l 3
              [0, 0, 0, 4],   # l 3
              [0, 0, 0, 5]]]  # o 4

argtest = tf.argmax(y_one_hot,1)
argtest_2 = tf.argmax(y_one_hot,2)
s = tf.Session()
s.run([argtest, argtest_2])

[array([[1, 0, 2, 5]], dtype=int64), array([[1, 0, 2, 3, 3, 3]], dtype=int64)]

In [10]:
t = tf.nn.embedding_lookup(params=y_one_hot, ids=[[0],[4]])
# tf.identity()
# tf.argmax()
t = tf.reduce_max([2,31,4,5])
# tf.sequence_mask()
# s.run(t)

In [62]:
from tensorflow.python.util import nest
tiled = tf.tile([[22,2,3]],(10,nest.flatten([256])[0]))
print(tiled)

Tensor("Tile_9:0", shape=(10, 768), dtype=int32)


In [75]:
tf.tile([[2,1,3]],[3,2])

<tf.Tensor 'Tile_19:0' shape=(3, 6) dtype=int32>

In [40]:
nest_pack_sequence = nest.pack_sequence_as(structure=256, flat_sequence=[tiled])
print(nest_pack_sequence)

Tensor("Tile_8:0", shape=(10, 768), dtype=int32)


In [46]:
tf_expanded_dims = tf.expand_dims(nest_pack_sequence,1)
print(tf_expanded_dims)

Tensor("ExpandDims_3:0", shape=(10, 1, 768), dtype=int32)


In [44]:
from tensorflow.python.ops.gen_array_ops import _concat_v2 as concat_v2

In [61]:
tf_rand_normed = tf.random_uniform([10,1,768], maxval=10, dtype=tf.int32)
concat_v2([tf_expanded_dims, tf_rand_normed], 1)
# tf.constant()


<tf.Tensor 'ConcatV2_3:0' shape=(10, 2, 768) dtype=int32>

In [10]:
a = tf.constant(np.array([[.1,.3,.5,.9],
                          [.01,.03,.10,.09]
                         ]))
s = tf.Session()
b = tf.nn.softmax(a)
argmxtext = tf.arg_max(a,1)
argmxtext = tf.argmax(a,1)
before_softmax, after_softmax, argm = s.run([a,b, argmxtext])
print(before_softmax)
print(after_softmax)
print(argm)

[[ 0.1   0.3   0.5   0.9 ]
 [ 0.01  0.03  0.1   0.09]]
[[ 0.16838508  0.205666    0.25120102  0.37474789]
 [ 0.23822781  0.24304033  0.26066275  0.25806911]]
[3 2]


In [8]:
c = tf.reduce_sum(a)
d = tf.reduce_mean(a)
reduced_sum, reduce_mean  = s.run([c,d])
print(reduced_sum, reduce_mean)

1.8 0.45


In [10]:
x = [[1,2,3],[3,3,502]]
e = tf.reduce_sum(x, axis=0)
f = tf.reduce_sum(x, axis=1)
row_sum, column_sum = s.run([e,f])
print(row_sum, column_sum)

[  4   5 505] [  6 508]


In [11]:
normal_x = preprocessing.normalize(x)
print(normal_x)

[[ 0.26726124  0.53452248  0.80178373]
 [ 0.00597588  0.00597588  0.99996429]]


In [16]:
a = tf.constant([2,3])
g = s.run([a])
print(g)

[array([2, 3])]


In [2]:

dd = tf.sigmoid(tf.constant([-.10,-20,200]))
logted_ = tf.log(dd)
meand = tf.reduce_mean(logted_)
ssd, logted, mea = s.run([dd, logted_, meand])
print(ssd, logted, mea)

NameError: name 's' is not defined

In [34]:
dd = tf.constant([.01102030239029302390])
s = tf.Session()
da = tf.clip_by_value(dd, clip_value_max=1-1e-2, clip_value_min=1e-2)
print(s.run([dd, da]))

[array([ 0.0110203], dtype=float32), array([ 0.0110203], dtype=float32)]
