In [20]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [12]:
a = tf.constant(np.array([[.1,.3,.5,.9]]))
s = tf.Session()
b = tf.nn.softmax(a)
before_softmax, after_softmax = s.run([a,b])
print(before_softmax)
print(after_softmax)

[[ 0.1  0.3  0.5  0.9]]
[[ 0.16838508  0.205666    0.25120102  0.37474789]]


In [16]:
c = tf.reduce_sum(a)
d = tf.reduce_mean(a)
reduced_sum, reduce_mean  = s.run([c,d])
print(reduced_sum, reduce_mean)

1.8 0.45


In [29]:
x = [[1,2,3],[3,3,502]]
e = tf.reduce_sum(x, axis=0)
f = tf.reduce_sum(x, axis=1)
row_sum, column_sum = s.run([e,f])
print(axis_sum, column_sum)

[3 3 3] [  6 508]


In [31]:
normal_x = preprocessing.normalize(x)
print(normal_x)

[[ 0.26726124  0.53452248  0.80178373]
 [ 0.00597588  0.00597588  0.99996429]]
