In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn import preprocessing



In [2]:
y_one_hot = [[[0, 1, 0, 0],   # i 1
              [1, 0, 0, 0],   # h 0
              [0, 0, 1, 0],   # e 2
              [0, 0, 0, 1],   # l 3
              [0, 0, 0, 1],   # l 3
              [0, 0, 0, -1]]]  # o 4
y_test = [[0,1,2,3,4],[1,2,3,4,5]]

In [3]:
out = tf.concat(y_one_hot, 0)
print(out)
s = tf.Session()
s.run(out)
with tf.variable_scope('rnn_decoder'):
    t = tf.get_variable_scope().reuse_variables()
    print(t)
    

Tensor("concat:0", shape=(6, 4), dtype=int32)
None


In [4]:
tf.contrib.rnn.LSTMStateTuple()

tensorflow.python.ops.rnn_cell_impl.LSTMStateTuple

In [20]:
y_one_hot_add = [[[0, 1, 0, 0]]]  # o 4
y_add = np.array(y_one_hot_add)
t = tf.constant(y_one_hot, dtype=tf.float32)
y = tf.constant(y_add, dtype=tf.float32)
t_y = tf.tanh(t+y)
print(t,y)
print(t+y)
s = tf.Session()
print(s.run(t+y))
print(s.run(t_y))
# v = tf.tanh(tf.matmul(tf.reshape(input_, [-1, hidden_size]), w) + tf.reshape(b ,[1,-1]))


Tensor("Const_31:0", shape=(1, 6, 4), dtype=float32) Tensor("Const_32:0", shape=(1, 1, 4), dtype=float32)
Tensor("add_28:0", shape=(1, 6, 4), dtype=float32)
[[[ 0.  2.  0.  0.]
  [ 1.  1.  0.  0.]
  [ 0.  1.  1.  0.]
  [ 0.  1.  0.  1.]
  [ 0.  1.  0.  1.]
  [ 0.  1.  0. -1.]]]
[[[ 0.          0.96402758  0.          0.        ]
  [ 0.76159418  0.76159418  0.          0.        ]
  [ 0.          0.76159418  0.76159418  0.        ]
  [ 0.          0.76159418  0.          0.76159418]
  [ 0.          0.76159418  0.          0.76159418]
  [ 0.          0.76159418  0.         -0.76159418]]]


In [13]:
y_one_hot = [[[0, 1, 0, 0],   # i 1
              [1, 0, 0, 0],   # h 0
              [0, 0, 1, 0],   # e 2
              [0, 0, 0, 1],   # l 3
              [0, 0, 0, 1],   # l 3
              [0, 0, 0, 1]]]  # o 4

argtest = tf.argmax(y_one_hot,1)
argtest_2 = tf.argmax(y_one_hot,2)
s = tf.Session()
s.run([argtest, argtest_2])

[array([[1, 0, 2, 3]], dtype=int64), array([[1, 0, 2, 3, 3, 3]], dtype=int64)]

In [10]:
a = tf.constant(np.array([[.1,.3,.5,.9],
                          [.01,.03,.10,.09]
                         ]))
s = tf.Session()
b = tf.nn.softmax(a)
argmxtext = tf.arg_max(a,1)
argmxtext = tf.argmax(a,1)
before_softmax, after_softmax, argm = s.run([a,b, argmxtext])
print(before_softmax)
print(after_softmax)
print(argm)

[[ 0.1   0.3   0.5   0.9 ]
 [ 0.01  0.03  0.1   0.09]]
[[ 0.16838508  0.205666    0.25120102  0.37474789]
 [ 0.23822781  0.24304033  0.26066275  0.25806911]]
[3 2]


In [8]:
c = tf.reduce_sum(a)
d = tf.reduce_mean(a)
reduced_sum, reduce_mean  = s.run([c,d])
print(reduced_sum, reduce_mean)

1.8 0.45


In [10]:
x = [[1,2,3],[3,3,502]]
e = tf.reduce_sum(x, axis=0)
f = tf.reduce_sum(x, axis=1)
row_sum, column_sum = s.run([e,f])
print(row_sum, column_sum)

[  4   5 505] [  6 508]


In [11]:
normal_x = preprocessing.normalize(x)
print(normal_x)

[[ 0.26726124  0.53452248  0.80178373]
 [ 0.00597588  0.00597588  0.99996429]]


In [16]:
a = tf.constant([2,3])
g = s.run([a])
print(g)

[array([2, 3])]


In [2]:

dd = tf.sigmoid(tf.constant([-.10,-20,200]))
logted_ = tf.log(dd)
meand = tf.reduce_mean(logted_)
ssd, logted, mea = s.run([dd, logted_, meand])
print(ssd, logted, mea)

NameError: name 's' is not defined

In [34]:
dd = tf.constant([.01102030239029302390])
s = tf.Session()
da = tf.clip_by_value(dd, clip_value_max=1-1e-2, clip_value_min=1e-2)
print(s.run([dd, da]))

[array([ 0.0110203], dtype=float32), array([ 0.0110203], dtype=float32)]
