# Softmax Classifier

In [1]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

In [2]:
x_data = [[1, 2, 1, 1], # Dim: 8 X 4
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],    # Dim: 8 X 3
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

In [3]:
W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

#### Do It Yourself

In [5]:
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = (tf.matmul(X, W) + b)   # Dim: 8 X 3

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(hypothesis, axis=1))   # reduce_sum까지하면 Dim이 8 X 1이 됨, reduce_mean을 하면 scalr가 됨

In [6]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [7]:
# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

    print('--------------')

    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.arg_max(a, 1)))

    print('--------------')

    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.arg_max(b, 1)))

    print('--------------')

    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.arg_max(c, 1)))

    print('--------------')

    all = sess.run(hypothesis, feed_dict={
                   X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.arg_max(all, 1)))

0 -22.5197
200 -3313.14
400 -6603.76
600 -9894.38
800 -13185.0
1000 -16475.7
1200 -19766.3
1400 -23057.0
1600 -26347.6
1800 -29638.3
2000 -32929.0
--------------
[[ 22220.49609375  22206.34960938  22228.5546875 ]] [2]
--------------
[[ 8784.82226562  8776.65722656  8778.45996094]] [0]
--------------
[[ 2127.70507812  2125.90966797  2126.34033203]] [0]
--------------
[[ 22220.49609375  22206.34960938  22228.5546875 ]
 [  8784.82226562   8776.65722656   8778.45996094]
 [  2127.70507812   2125.90966797   2126.34033203]] [2 0 0]
